POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "j Doe",
    "email": "j@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "9c5bf951-2af8-4450-bf7d-22e57429b5c2"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "9476dbc4-479d-4286-a976-12c63386451b",
    "account_id_to": "0005d381-2e6d-4cb0-a4f7-6fb94c8a69c0",
    "amount": 100
}