POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "j@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e1723f22-687e-48db-bfa8-24c695783b03"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "198557c3-5cba-4421-a48f-aa52b9bdfc43",
    "account_id_to": "20832441-d400-4a74-8413-795a65d739d3",
    "amount": 100
}

###

GET http://localhost:3003/balances/198557c3-5cba-4421-a48f-aa52b9bdfc43 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3003/balances/20832441-d400-4a74-8413-795a65d739d3 HTTP/1.1
Content-Type: application/json
